[package]
name = "advent-of-code-2024"
version = "0.1.0"
edition = "2021"
default-run = "advent-of-code-2024"

[dependencies]
aoc-client = "0.2.0"
chrono = "0.4.38"
clap = { version = "4.5.23", features = ["derive"] }
itertools = "0.13.0"
ndarray = "0.16.1"
regex = "1.11.1"
